# Setting profile
spring:
  config:
    activate:
      on-profile: prod

#   MySQL Database Configuration
  datasource:
    url: jdbc:mysql://35.200.204.16:3306/categorydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
