# Spring Application Name
spring:
  application:
    name: CategoryProduct
  profiles:
    active: dev

# Disable config
pubsub:
  enabled: false

# GCP Cloud configuration
cloud:
  gcp:
    project-id: gke-springboot-472605
    credentials:
      location: classpath:springboot-app-457506-459b9c19321c.json

# Logging Configuration
logging:
  level:
    root: INFO
    com.Rest.CategoryProduct: DEBUG
  file:
    name: CategoryProduct/logs/application.log

# Prometheus / Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      all: true
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true

# Kafka Config (commented for now)
# kafka:
#   bootstrap-servers: localhost:9092
#   consumer:
#     group-id: ecom-group
#     auto-offset-reset: earliest
#     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#   producer:
#     key-serializer: org.apache.kafka.common.serialization.StringSerializer
#     value-serializer: org.apache.kafka.common.serialization.StringSerializer
