spring:
  cloud:
    vault:
      uri: http://34.180.3.84:8200
      token: root
      kv:
        enabled: true
        backend: secret
        default-context: gcp/cloudsql/categorydb
  datasource:
    url: http://34.180.3.84:3306
    username: ${spring.cloud.vault.database.username}
    password: ${spring.cloud.vault.database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
